name: Validate Wordle Solution List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_wordle_list:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Wordle solution list line count
        run: |
          URL="https://gist.githubusercontent.com/cfreshman/a03ef2cba789d8cf00c08f767e0fad7b/raw/c46f451920d5cf6326d550fb2d6abb1642717852/wordle-answers-alphabetical.txt"

          # Check HTTP status
          status_code=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ "$status_code" -ne 200 ]; then
            echo "URL is not valid, returned status $status_code"
            exit 1
          fi

          # Fetch content and remove blank/whitespace lines
          total_words=$(curl -s "$URL" | sed '/^[[:space:]]*$/d' | wc -l)

          if [ "$total_words" -lt 2300 ]; then
            echo "Word list too short: $total_words words (minimum 2300 required)"
            exit 2
          fi

          echo "Wordle solution list has $total_words words (ok)"
